### ISSUE TITLE
Support Android NDK platform

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenZWave/open-zwave#212]
```
Thank you for your suggestion.

I tried that of course ;-)
Android is missing some standard linux libraries to make it work.
The hidapi part of the code won't compile.
Also the way threads are implemented in openzwave is not supported (things like 
PTHREAD_CANCEL_ENABLE are blocked 
(https://groups.google.com/group/android-ndk/tree/browse_frm/thread/b33991121d61
5e12/29949daae0a38205?hide_quotes=no)).

Maybe it can be fairly easy by rewriting just that thread part of openzwave, 
but there is still no guarantee that the hidapi part will work. (the usb 
controller already shows up as /dev/ttyUSB0, which is good i presume?)
Maybe there are some more things missing that I haven't even tried to compile 
yet.
I'm not that great with c/c++ and low level programming, so still any help 
would be greatly apreciated.

Willem

```

Original issue reported on code.google.com by `glsatz` on 14 Apr 2013 at 2:48

**Comment by mcallegari** [comment]
Hi, as anticipated back in January, I've started to dig into building OZW with the Google NDK.
So far I've started to create two patches:
- one environment variable to disable the HIDAPI integration
- the addition throughout the code of an ifdef ANDROID to handle the cases where the NDK doesn't support the original code.

I managed to build the static version of OZW. Shared library fails to link cause of some toolchain issue.
If you are still interested in this activity, I could share the patches as PR.

Please keep in mind this is not finished and not even tested (waiting for some kernel drivers to test the serial interface)
Also there are serious considerations to be made on threads, where pthread_setcancelstate and pthread_cancel don't even exist in the NDK.
I googled for code alternatives, but the final word is for the project owners.

**Comment by Fishwaldo** [comment]
I think I'd prefer you to keep it as a separate fork for now. I wont merge a incomplete PR. :)

Also - You should try to implement the Android support as a separate platform rather than #ifdef'ing stuff around. That helps us make sure that changes to one platform does not break another. 

As far as threading goes... its integrated deeply in OZW. I doubt very much you could make it work (well) without threading, so I suggest you keep researching...

**Comment by satzg** [comment]
The suggestion of a separate platform will be much cleaner and easier to support, especially as you discover different operating system differences. As for the threads, if I recall correctly, the pthread cancel feature was only used to terminate an application using the library properly. Without it the unix input read thread would hang waiting for something to be read and the destructor routines would never return. You might be able to find another way to do this under Android.

**Comment by mcallegari** [comment]
Well, I don't understand how you guys can judge a patch without even seeing it.
You called the platform implementation "unix" and not "linux".
In fact, the DARWIN support (which is a *nix platform) is ifdef'ed in the code.

Same thing is Android. It's a *nix platform, inheriting 99% of the POSIX code of a *nix platform.

I'll keep on researching about threads and friends when the time comes for me to test the code on Android, but don't count on me  introducing a new platform into OZW.

**Comment by Fishwaldo** [comment]
No one is judging. You yourself said it's not complete and not tested. 

While Andriod runs the Linux kernel, it's clear that they don't have a standard C++ library, otherwise there would be full pthread support. For the sake of maintainability I'd prefer a separate directory. If some changes need to go into the core library we can look at abstracting it out to platform code if necessary.

**Comment by mcallegari** [comment]
It's not complete, yes, but are you aware that here on GitHub a Pull Request can be commented, improved, merged or eventually closed ?
It's not necessarily something that will go mainstream if it's not OK, but at least a discussion can be started upon it.

> While Andriod runs the Linux kernel, it's clear that they don't have a standard C++ library, otherwise there would be full pthread support. For the sake of maintainability I'd prefer a separate directory. If some changes need to go into the core library we can look at abstracting it out to platform code if necessary.

Again, it's clear to me that you are talking without having evaluated the entity of the patch. Moreover projects like Qt (entirely written in C++) runs perfectly fine on Android. So I don't see what's the problem here.

Anyway, the HIDAPI patch is generic and it's not specifically related to Android.

**Comment by mcallegari** [comment]
For the sake of sharing information, here's what Qt did on threads;
https://github.com/qtproject/qtbase/blob/dev/src/corelib/thread/qthread_unix.cpp

As you can see, they simply ifdef'ed the pthread_setcancelstate calls.

Exactly what I did.

**Comment by Fishwaldo** [comment]
Have a look at my "TODO" list as far as the outstanding issues etc. I'm not going to review something that has not even had a basic testing done. For all I know, there might be more work that is required to get it working beyond just a compile test. 

And comparing QT to OZW is like comparing a 18 wheeler truck to a Mini. QT is a beast. It has dozens, if not 100's of developers and countless more users. Just cause QT works doesn't mean OZW will. One of the reasons I ask for a separate platform directory is because I see things eventually needing a customized solution for Android. Is it realistic to log anything on Android, given that users probably can't access those logs. Even if we do log, are megabytes of Logs relevant. Should we just put in a abstract Log Implementation and tell Andriod developers to do their own logging implementation. Can you log to the "current working directory" (if such a thing exists in andriod) - I know on iOS you can't, so we need to address that. 

And thats just logging... (I'm not asking you to do something about Logging, FYI, I'm just using it as a justification).

Until you can get some actual testing done, and validate your changes, asking me to review it is pointless.

If your not happy with my workflow, you are free to keep it as a fork and do it the way you want. Thats one of the advantages of GitHub.

**Comment by mcallegari** [comment]
@Fishwaldo I totally understand your view and I respect your workflow, don't worry.
> And comparing QT to OZW is like comparing a 18 wheeler truck to a Mini.
:laughing: Not comparing, just showing how other developers dealt with threads on Android.
I also thought they created a separate implementation, but then I realized they just ifdef'ed.

In general though, my opinion about targets (and basically comparisons as well) is like when we were at school: on a scale of marks from 1 to 10, if you aim to 10, you'll probably get a 8 or 9. If you aim to 6 (which let's say it's the "sufficiency" target), you'll probably get 5 or less.

So if you want OZW to be an excellent software, you need to aim to 10 :smiley: 
Not judging ! Just my humble point of view. Qt is indeed a monster, but there's a lot to learn from it. And since we're developers, we're not scared to learn, are we ? :stuck_out_tongue_winking_eye: 

Then if you tell me Qt has much more manpower than OZW, I perfectly agree. (even though they have huge issues in maintaining some modules like QtMultimedia cause of lack of resources) 
I do myself have a project and at the moment there are 3 core developers working on it in their spare time, so I perfectly understand how difficult it is to carry on an open source project.

Let's do this. I'll give you peace :smile: and as soon as I can test the build I'll report the results.
Then we can talk if/when/how to review the code.

Thanks for your time in any case !

**Comment by svoulaz** [comment]
@mcallegari I was wondering if you've been successful in porting OZW to Android - very interesting. Any news?

**Comment by laibulle** [comment]
I am very interested too.

**Comment by koush** [comment]
I've implemented this.
Two commits:

https://github.com/koush/open-zwave/commit/d2439fbfa7cf54556092e6589a20fe85c3718aae

https://github.com/koush/open-zwave/commit/3235375e1d2526e0b63032b86a302b532f7c8c8a

**Comment by Fishwaldo** [comment]
If this works, please submit a pull request... although, I wont take a cmake build, please see if you can do the same with the Makefiles. (i dont see anything special in the Cmakeslist.txt that warrants a new build system bundled with OZW)

**Comment by Fishwaldo** [comment]
Closing. No PR was submitted.

**Comment by iksheth** [comment]
> I've implemented this. You'll need a Cmakeslist.txt that includes all the source files.
> 
> ```
> cmake_minimum_required(VERSION 3.4.1)
> 
> 
> add_library(
>         tinyxml
>         STATIC
> 
>         ../../../open-zwave/cpp/tinyxml/tinyxml.cpp
>         ../../../open-zwave/cpp/tinyxml/tinyxmlparser.cpp
>         ../../../open-zwave/cpp/tinyxml/tinyxmlerror.cpp
>         ../../../open-zwave/cpp/tinyxml/tinystr.cpp)
> 
> target_include_directories(tinyxml PRIVATE ../../../open-zwave/cpp/tinyxml)
> 
> target_link_libraries(
>         tinyxml
> 
>         ${log-lib} )
> 
> foreach (src_dir src src/command_classes tinxml src/value_classes src/platform src/platform/unix src/aes)
> file(GLOB src
>         ../../../open-zwave/cpp/${src_dir}/*.cpp
>         )
> list(APPEND src_files ${src})
> file(GLOB src
>         ../../../open-zwave/cpp/${src_dir}/*.c
>         )
> list(APPEND src_files ${src})
> list(APPEND include_dirs ../../../open-zwave/cpp/${src})
> endforeach(src_dir)
> 
> add_library(
>         open-zwave
>         STATIC
>         ${src_files})
> 
> target_include_directories(open-zwave PRIVATE ../../../open-zwave/cpp/src ../../../open-zwave/cpp/open-zwave/cpp/tinyxml ../../../open-zwave/cpp/tinyxml)
> 
> target_link_libraries(
>         open-zwave
> 
>         ${log-lib} tinyxml )
> 
> add_library(
>             native-lib
>             SHARED
> 
>             # make this version file using host build on command line:
>             # make -j16 cpp/src/vers.cpp
>             src/main/cpp/vers.cpp
> 
>             src/main/cpp/native-lib.cpp )
> 
> 
> target_link_libraries(
>         native-lib
>         ${log-lib} tinyxml open-zwave )
> 
> find_library(
>         log-lib
>         log )
> 
> target_include_directories(native-lib PRIVATE src/main/cpp/hidapi/android src/main/cpp/hidapi/hidapi src/main/cpp/libusb/libusb ../../../open-zwave/cpp/src )
> ```
> 
> Two commits:
> 
> [koush@d2439fb](https://github.com/koush/open-zwave/commit/d2439fbfa7cf54556092e6589a20fe85c3718aae)
> 
> [koush@3235375](https://github.com/koush/open-zwave/commit/3235375e1d2526e0b63032b86a302b532f7c8c8a)

Did this worked ?
