### ISSUE TITLE
Thermostat not respdoning to certain instances of ThermostatSetpointCmd_Get

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenZWave/open-zwave#422]
```
What steps will reproduce the problem?
1.Add Honeywell TH8320ZW thermostat to network
2.Start openzwave (via python-openzwave)
3.

What is the expected output? What do you see instead?
Expected network ready to quickly
Actually takes over four minutes due to thermostat not responding to two 
ThermostatSetpointCmd_Get commands (seem to be Furnace and DryAir)

What version of the product are you using? On what operating system?
python-openzwave-0.2.6
openzwave-1.2.919
CentOS6 (Linux pro1000dev.atlantic 2.6.32-504.1.3.el6.x86_64 #1 SMP Tue Nov 11 
17:57:25 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux)

What branch of the code were you using? (if you just followed the
instructions on the source checkout page, then say trunk.. if you checked
out a branch, please let us know what branch it was)
trunk

Please include the file OZW_Log.txt from your program. Make sure the file
zwcfg*.xml is NOT present.

Please provide any additional information below.

In OZW log see line 835 which adds setpoint Furnace and lines 1394 - 1414 in 
which thermostat fails to respond.


```

Original issue reported on code.google.com by `eldonz.h...@gmail.com` on 25 Dec 2014 at 6:24

Attachments:
- [OZW_Log.log.thermostat.txt](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-422/comment-0/OZW_Log.log.thermostat.txt)

**Comment by madarwin** [comment]
I believe my thermostat (Honeywell) has the same issue. 

You can see in the OP's log, his thermostat mode supports 'Heat Econ' and 'Cool Econ'. There are supposed to be setpoints for these instead of Furnace and Dry Air. 

After the index is calculated in ThermostatSetpoint:HandleMsg
 int32 index = (int32)((i-1)<<3) + bit + m_setPointBase;

Just add the following to adjust the higher up setpoints. My code might not be correct for other thermostats... but it works for me (and it should work for OP). There is probably some magical formula for this....but I have not investigated much.

int32 index_p;
if (index > 3) {
    index_p = index + 4;
} else {
    index_p = index;
}

MD

**Comment by madarwin** [comment]
Oh and adjust the other lines to use the new index.
