### ISSUE TITLE
Invalid value ÿ in log message when setting value for COMMAND_CLASS_SWITCH_MULTILEVEL

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenZWave/open-zwave#466]
```
I noticed when setting a value for a COMMAND_CLASS_SWITCH_MULTILEVEL that there 
appears in the log an invalid character.

This might also happen for other classes

Log output:
2015-02-27 10:39:57.053 Info, Node011, Value::Set - 
COMMAND_CLASS_SWITCH_MULTILEVEL - Level - 0 - 1 - ÿ

notice the ÿ in the message

With kind regards,
Rob
```

Original issue reported on code.google.com by `gizmo...@gmail.com` on 27 Feb 2015 at 9:48

**Comment by armills** [comment]
I don't have a dev environment set up, but the reason is that when converting uint8 to strings, C++ treats them as characters. We should be able to fix it by casting to a uint16/uint32 before conversion. This would also make the method symmetric with SetFromString

https://github.com/OpenZWave/open-zwave/blob/master/cpp/src/value_classes/ValueByte.cpp#L84
```c++
ss << (uint32)GetValue();
```

http://stackoverflow.com/questions/33050355/stringstream-uint8-t-in-hex-c
