### ISSUE TITLE
Basic sets from contact sensors not working

### ISSUE THREAD

**Issue by ffontaine** [OpenZWave/open-zwave#498]
With latest release of domoticz and OZW, the FGK101 sensor stopped working, I'm not the only one as the post http://www.domoticz.com/forum/viewtopic.php?f=6&t=4869 has been updated in March 12th.

The issue seems related to a closed issue: https://github.com/OpenZWave/open-zwave/issues/408.

I have the following traces:
2015-04-02 11:23:07.090 Detail, Node005,   Received: 0x01, 0x09, 0x00, 0x04, 0x00, 0x05, 0x03, 0x20, 0x01, 0xff, 0x2a
2015-04-02 11:23:07.093 Detail, 
2015-04-02 11:23:07.094 Info, Node005, Received Basic set from node 5: level=255. Treating it as a Basic report.

Best Regards,

Fabrice

**Comment by ualex73** [comment]
Without the OZW_Log.txt and zwcfg*xml we can't say anything about it.

**Comment by ualex73** [comment]
BTW: did you try the latest open-zwave trunk also? This looks to have solved this #408 issue.

https://groups.google.com/forum/#!topic/openzwave/JHXf728A5uU

**Comment by ffontaine** [comment]
I'm using the latest release of open-zwave trunk (rev 892).
You can find the log files here: https://gist.github.com/ffontaine/c05ea1d06db497a1ec47

**Comment by ualex73** [comment]
The logging already shows:

2015-04-02 10:59:13.399 Info, Node005, Response RTT 28 Average Response RTT 28
2015-04-02 10:59:13.400 Info, Node005, Received Basic report from node
5: level=255
2015-04-02 10:59:13.402 Warning, Node005, No Valid Mapping for Basic
Command Class and No ValueID Exported. Error?
2015-04-02 10:59:13.403 Detail, Node005,   Expected reply and command
class was received
2015-04-02 10:59:13.405 Detail, Node005,   Message transaction complete

This means for this device, no basic -> specific commandclass mapping is in
place.

According to the config files in open-zwave and your zwcfg*xml, it should
be there ... So that's something to look into.

2015-04-02 13:01 GMT+02:00 Fabrice Fontaine <notifications@github.com>:

**Comment by Fishwaldo** [comment]
Basic sets on a sleeping device is never going to work well with OZW. 

You need to see if there is a config option to get it to change what it reports. 

The No Mapping error is because the device probably hasn't completed it's queryStages. Around 11:14 it completes. (For node 5)

https://github.com/OpenZWave/open-zwave/wiki/Basic-Command-Class

**Comment by Fishwaldo** [comment]
Looking at the config, try changing param 5 to something other than 255. We should probably alter the default in the config file as it's set to BasicSet. 

https://github.com/OpenZWave/open-zwave/blob/master/config/fibaro/fgk001.xml

**Comment by ffontaine** [comment]
It works if I set the default value for parameter 5 to "ALARM GENERIC" instead of "BASIC_SET" in the configuration file, thank you.

**Comment by rgroothuis** [comment]
Even with parameter 5 set to "ALARM GENERIC" I cannot get the Fibaro FGK101 to report its open/close status into Openzwave control panel. Only when I hit the button a couple of times, so the device wakes up, the status is reported into Openzwave and this into Domoticz. 
I'm using Domoticz V2.3530 and Openzwave Version: 1.3-523-gb258e9e. 
The Fibaro sensor information: library version 3, protocol version 3.42 and application version 2.01. 

Any suggestions?

**Comment by nechry** [comment]
Is occured before the interview (query stage) is compited?

**Comment by rgroothuis** [comment]
Not sure if I understand your question and if it is linked to my post. 

The device is fully regonised within Openzwave. The interview is absolutely completed and correct. I can even change the parameters successfully, in other words I can communicate with the device. 

When I chande the magnetic away from the sensor and I push the button a couple of times then the status is reported back into Openzwave and Domoticz.

**Comment by Fishwaldo** [comment]
Battery powered devices and basic CC don't work well. See https://github.com/OpenZWave/open-zwave/wiki/Basic-Command-Class

It sounds like it's not accepting the Alarm Generic setting.
